### ISSUE TITLE
Failing only Macy tests

### ISSUE THREAD

**Issue by mayork** [hoburg/SPaircraft#80]
We're only failing tests on the macys machine. @bqpd I'm thinking this isn't our problem? This is the terminal print out...

```
Error Message

Command '['mskexpopt', '/var/folders/wp/20zl4b2n0qxcrp90f31275f80000gp/T/tmpWtYoUY/gpkit_mosek']' returned non-zero exit status 152
Stacktrace

Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/tests/helpers.py", line 62, in test
    testfn(name, import_dict, path)(self)
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/tests/from_paths.py", line 54, in <lambda>
    lambda self: getattr(self, name)()))  # pylint:disable=undefined-variable
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/tests/from_paths.py", line 45, in test_fn
    mod.test()
  File "SP_aircraft.py", line 1420, in test
    run_737800()
  File "SP_aircraft.py", line 269, in run_737800
    sol = m_relax.localsolve(verbosity=4, iteration_limit=200, reltol=0.01)
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/constraints/prog_factories.py", line 84, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/constraints/signomial_program.py", line 124, in localsolve
    result = primal_feas.solve(solver, verbosity=verbosity-1)
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/constraints/geometric_program.py", line 173, in solve
    k=self.k, *args, **kwargs)
  File "/Users/jenkins/workspace/gpkit_ResearchModel_d8_Push/buildnode/macys/optimizer/mosek/gpkit/gpkit/_mosek/cli_expopt.py", line 86, in imize
    for logline in check_output(["mskexpopt", filename]).split(b"\n"):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['mskexpopt', '/var/folders/wp/20zl4b2n0qxcrp90f31275f80000gp/T/tmpWtYoUY/gpkit_mosek']' returned non-zero exit status 152
```

**Comment by mayork** [comment]
now the same issue is on all the mosek tests

**Comment by mayork** [comment]
and now just on the Win64 machine...

**Comment by bqpd** [comment]
Dang. This still happening?

**Comment by whoburg** [comment]
seems like these tests are still failing, would be good to resolve before Armstrong meeting (week after next), since nasa folks there may be interested in cloning/using our code

**Comment by 1ozturkbe** [comment]
it seems like this is no longer an issue? do we know why it occurred?

**Comment by mayork** [comment]
seems to not be an issue
